platform :ios, '7.0'

target 'HWCoreFramework' do
    pod 'HWCoreFramework', :path => '../'
    pod 'Aspects'
    pod 'Masonry'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'MJRefresh'
    pod 'ReactiveCocoa'
    pod 'FDStackView'
end
