source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'HWCoreFramework', :path => '../'
pod 'Aspects'
pod 'Masonry'
pod 'UITableView+FDTemplateLayoutCell'
pod 'MJRefresh'
pod 'ReactiveCocoa'
pod 'FDStackView'