source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
target 'HWCoreFramework_Example' do
  pod 'HWCoreFramework', :path => '../'
  pod 'Aspects'
  pod 'Masonry'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'MJRefresh'
end
